spring:
  application:
    name: g59-spring-ai

  ai:
    retry:
      max-attempts: 1

    openai:
      api-key: ${OPENAI_API_KEY}
      # base-url: https://api.openai.com/
      chat:
        options:
          model: gpt-4o
          max-tokens: 1024
          temperature: 0.2



    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: always




  datasource:
    url: jdbc:mysql://localhost:3306/AI_CHAT?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Europe/Berlin
    username: root
    password: root

